version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /var/task
      - cp LICENSE /var/task/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /var/task/LICENSE
  discard-paths: yes